/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author computer
 */
public class Interfata extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfata.class.getName());

    /**
     * Creates new form Interfata
     */
    
    private java.util.List<Student> studenti = new java.util.ArrayList<>();

static class Student {
    private String nume, prenume, specializare;
    private int an;
    private double media;
    private boolean bursier;

    public Student(String n, String p, int a, String s, double m, boolean b) {
        nume = n; prenume = p; an = a; specializare = s; media = m; bursier = b;
    }

    public String getNume() { return nume; }
    public String getPrenume() { return prenume; }
    public String getSpecializare() { return specializare; }
    public double getMedia() { return media; }

    @Override
    public String toString() {
        return nume + " " + prenume + " | An: " + an + " | " + specializare +
               " | Media: " + media + " | " + (bursier ? "Bursier" : "Nebursier");
    }
}

    public Interfata(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rbAn1.setSelected(true); // selectăm implicit anul I
        textArea.setEditable(false);
        spinnerMedia.setModel(new javax.swing.SpinnerNumberModel(0.0, 0.0, 10.0, 0.1));


        
       
btnAdauga.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        adaugaStudent();
    }
});

btnSortAlfabetic.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        sorteazaAlfabetic();
    }
});

btnSortMedia.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        sorteazaDupaMedia();
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void adaugaStudent() {
    String n = txtNume.getText().trim();
    String p = txtPrenume.getText().trim();
    int an = rbAn1.isSelected() ? 1 : 2;
    String spec = (String) comboSpecializare.getSelectedItem();
    boolean bursier = chkBursier.isSelected();
    double med = ((Number) spinnerMedia.getValue()).doubleValue();

    if (n.isEmpty() || p.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Completează numele și prenumele!");
        return;
    }

    studenti.add(new Student(n, p, an, spec, med, bursier));
    afiseazaStudenti();
    
     // Resetare câmpuri după adăugare
    txtNume.setText("");
    txtPrenume.setText("");
    rbAn1.setSelected(true);
    comboSpecializare.setSelectedIndex(0);
    chkBursier.setSelected(false);
    spinnerMedia.setValue(0.0);
    txtNume.requestFocus(); 
    
    
    
}

private void sorteazaAlfabetic() {
    studenti.sort(java.util.Comparator.comparing(Student::getSpecializare)
                                     .thenComparing(Student::getNume)
                                     .thenComparing(Student::getPrenume));
    afiseazaStudenti();
}

private void sorteazaDupaMedia() {
    studenti.sort(java.util.Comparator.comparing(Student::getSpecializare)
                                     .thenComparing(java.util.Comparator.comparingDouble(Student::getMedia).reversed()));
    afiseazaStudenti();
}

private void afiseazaStudenti() {
    StringBuilder sb = new StringBuilder();
    for (Student s : studenti) sb.append(s).append("\n");
    textArea.setText(sb.toString());
}

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbAn1 = new javax.swing.JRadioButton();
        rbAn2 = new javax.swing.JRadioButton();
        comboSpecializare = new javax.swing.JComboBox<>();
        chkBursier = new javax.swing.JCheckBox();
        spinnerMedia = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        txtNume = new javax.swing.JTextField();
        txtPrenume = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAdauga = new javax.swing.JButton();
        btnSortAlfabetic = new javax.swing.JButton();
        btnSortMedia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(rbAn1);
        rbAn1.setText("I");

        buttonGroup1.add(rbAn2);
        rbAn2.setText("II");

        comboSpecializare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatica", "Matematica", "Economie" }));

        chkBursier.setText("da");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        txtNume.setCaretColor(new java.awt.Color(102, 204, 255));
        txtNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nume");

        jLabel2.setText("Prenume");

        jLabel3.setText("Specializare");

        jLabel4.setText("An");

        jLabel5.setText("Bursier");

        jLabel6.setText("Media");

        btnAdauga.setBackground(new java.awt.Color(255, 204, 204));
        btnAdauga.setText("Adauga");
        btnAdauga.setOpaque(true);

        btnSortAlfabetic.setBackground(new java.awt.Color(204, 204, 255));
        btnSortAlfabetic.setText("Sortare specializare+alfabetic");
        btnSortAlfabetic.setOpaque(true);

        btnSortMedia.setBackground(new java.awt.Color(204, 204, 255));
        btnSortMedia.setText("Sortare specializare+medie");
        btnSortMedia.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkBursier)
                                            .addComponent(spinnerMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbAn1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(rbAn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(comboSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txtPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAdauga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSortAlfabetic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSortMedia)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSpecializare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbAn1)
                            .addComponent(rbAn2)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addComponent(chkBursier)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdauga)
                    .addComponent(btnSortAlfabetic)
                    .addComponent(btnSortMedia))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Interfata dialog = new Interfata(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdauga;
    private javax.swing.JButton btnSortAlfabetic;
    private javax.swing.JButton btnSortMedia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkBursier;
    private javax.swing.JComboBox<String> comboSpecializare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAn1;
    private javax.swing.JRadioButton rbAn2;
    private javax.swing.JSpinner spinnerMedia;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField txtNume;
    private javax.swing.JTextField txtPrenume;
    // End of variables declaration//GEN-END:variables
}
